PROMPTS: list[str] = [
    "The worst thing to bring to a job interview is ___.",
    "Scientists just discovered that ___ is actually good for you.",
    "The one thing everyone should do before they die is ___.",
    "Nothing ruins a first date faster than ___.",
    "My therapist told me I need to stop thinking about ___.",
    "The real reason aliens haven't visited Earth is ___.",
    "I didn't realize ___ was weird until I tried it at someone else's house.",
    "The secret ingredient that makes this dish perfect is ___.",
    "___ would be a terrible name for a children's book.",
    "Historians will remember this generation for ___.",
    "Nothing says 'I love you' quite like ___.",
    "The next great Olympic sport will be ___.",
    "My doctor told me to cut back on ___.",
    "The biggest surprise at the funeral was ___.",
    "You know you're getting old when ___ starts to seem reasonable.",
    "I've spent way too much money on ___.",
    "___ is the leading cause of awkward silences.",
    "The one thing I wish I could unsee is ___.",
    "On my deathbed, I will regret never having tried ___.",
    "My life changed forever the day I discovered ___.",
    "The world would be a better place without ___.",
    "If I had a dollar for every time someone said ___, I'd be rich.",
    "Nothing brings a family together like ___.",
    "The real reason I'm still single is ___.",
    "I'd rather eat ___ than listen to another minute of this.",
    "My greatest hidden talent is ___.",
    "The one food I could eat every day for the rest of my life is ___.",
    "They said ___ would change the world. They were not wrong.",
    "Someday I will write a memoir titled: ___.",
    "The most polite way to describe ___ is 'an acquired taste'.",
]
