class RoomNotFoundError(Exception): ...
class RoomFullError(Exception): ...
class PermissionDeniedError(Exception): ...
class PlayerNotFoundError(Exception): ...
class NotEnoughPlayersError(Exception): ...
class GameAlreadyStartedError(Exception): ...
class GameNotStartedError(Exception): ...
class InvalidGameStateError(Exception): ...
